export default {
	'PHAST.GT.1': '武士道',
	'PHAST.GT.2': '金錢貓',
	'PHAST.GT.3': '百鬼夜行',
	'PHAST.GT.4': '美人魚',
	'PHALE.GT.1': '百家樂',
	'PHALE.GT.98': 'Jackpot Bonus',
	'PHALE.GT.99': 'Jackpot BigWin',
	'PHAGO.GT.HL60': '漲跌1分鐘',
	'PHAGO.GT.HL180': '漲跌3分鐘',
	'PHAGO.GT.HL300': '漲跌5分鐘',
	'PHAGO.GT.ST30': '區間30秒',
	'PHAGO.GT.ST60': '區間60秒',
	'PHAGO.GT.ST120': '區間120秒',
	'PHAGO.GT.ST300': '區間300秒',
	'PHA3D.GT.wealthgod': '黃金財神',
	'PHA3D.GT.chinpingmei': '金瓶梅',
	'PHA3D.GT.egyptfirewheel': '埃及風火輪',
	'PHA3D.GT.condorhero': '神雕仙俠',
	'PHA3D.GT.longfeng': '龍鳳全席',
	'PHABL.GT.1': '六合彩',
	'PHABL.GT.2': '大樂透',
	'PHABL.GT.3': '今彩539',
	'PHABL.PT.1': '特別號',
	'PHABL.PT.2': '全車',
	'PHABL.PT.3': '二星',
	'PHABL.PT.4': '三星',
	'PHABL.PT.5': '四星',
	'PHABL.PT.6': '天碰二',
	'PHABL.PT.7': '天碰三',
	'PHABL.PT.8': '台號',
	'PHABL.PT.9': '特尾三',
	'PHABL.PT.10': '組合/球色',
	'PHABL.PT.11': '生肖',
	'PHALT.GT.1': '天津時時彩',
	'PHALT.GT.2': '新疆時時彩',
	'PHALT.GT.3': '重慶時時彩',
	'PHALT.GT.4': '北京PK',
	'PHALT.GT.5': '賓果賓果',
	'PHALT.GT.6': '北京快樂8'
}
